"""End-to-end demo for the PDF editor.

Builds a small PDF with several fonts/sizes/colors, inspects it, edits it,
then re-inspects to prove every replaced span kept the original formatting.
"""

from __future__ import annotations

from pathlib import Path

import fitz

from pdf_editor import PDFEditor, PDFInspector


HERE = Path(__file__).resolve().parent
SAMPLE = HERE / "sample.pdf"
EDITED = HERE / "sample_edited.pdf"


# Each tuple: (text, x, y, fontname, size, color)
SAMPLE_SPANS: list[tuple[str, float, float, str, float, tuple[float, float, float]]] = [
    # title - bold sans, navy
    ("Quarterly Report",          72, 100, "hebo", 24, (0.10, 0.20, 0.55)),
    # subtitle - italic sans, gray
    ("Generated by PDF Editor",   72, 132, "heit", 12, (0.45, 0.45, 0.45)),
    # body - serif black
    ("Total revenue: 12500 INR",  72, 190, "tiro", 12, (0.00, 0.00, 0.00)),
    ("Customer count: 240 buyers",72, 212, "tiro", 12, (0.00, 0.00, 0.00)),
    ("Growth: 15 percent QoQ",    72, 234, "tiro", 12, (0.00, 0.00, 0.00)),
    # bold callout - red
    ("STATUS: ON TRACK",          72, 280, "hebo", 16, (0.75, 0.10, 0.10)),
    # mono code - dim
    ("build = v1.0.0",            72, 330, "cour", 11, (0.20, 0.20, 0.20)),
    # serif italic dark green
    ("Confidential — internal",   72, 380, "tiit", 10, (0.10, 0.40, 0.20)),
]


def build_sample() -> None:
    doc = fitz.open()
    page = doc.new_page(width=595, height=842)  # A4
    for text, x, y, font, size, color in SAMPLE_SPANS:
        page.insert_text((x, y), text, fontname=font, fontsize=size, color=color)
    doc.save(SAMPLE)
    doc.close()


def show_spans(label: str, ins: PDFInspector) -> None:
    print(f"\n{label}")
    print("-" * len(label))
    for s in ins.iter_spans():
        print(f"  {s.text!r:<32}  font={s.font:<24} size={s.size:>5}  "
              f"color={s.color_hex}  style={s.style_summary()}")


def main() -> int:
    print(f"[1] building sample at {SAMPLE.name}")
    build_sample()

    print("\n[2] inspecting sample")
    with PDFInspector(SAMPLE) as ins:
        r = ins.report()
        print(f"  pages       : {r['pages']}")
        print(f"  fonts used  : {list(r['fonts_used'].keys())}")
        print(f"  colors used : {list(r['colors_used'].keys())}")
        print(f"  sizes used  : {list(r['sizes_used'].keys())}")
        show_spans("all spans BEFORE edit", ins)

    edits = [
        ("12500", "15750"),
        ("240",   "318"),
        ("15 percent", "22 percent"),
        ("ON TRACK", "AHEAD"),
        ("v1.0.0", "v1.1.0"),
    ]

    print(f"\n[3] applying {len(edits)} edits and saving to {EDITED.name}")
    with PDFEditor(SAMPLE) as ed:
        total = 0
        for find, replace in edits:
            n = ed.replace_text(find, replace)
            print(f"  {find!r:<14} -> {replace!r:<14}  ({n} span(s))")
            total += n
        ed.save(EDITED)
        print(f"  total spans modified: {total}")
        if ed.warnings:
            print(f"  warnings ({len(ed.warnings)}):")
            for w in ed.warnings:
                print(f"    - {w}")

    print("\n[4] re-inspecting edited PDF")
    expectations = {
        "15750":      ("Times-Roman", 12.0, "#000000"),
        "318":        ("Times-Roman", 12.0, "#000000"),
        "22 percent": ("Times-Roman", 12.0, "#000000"),
        "AHEAD":      ("Helvetica-Bold", 16.0, "#bf1a1a"),
        "v1.1.0":     ("Courier",     11.0, "#333333"),
    }
    fails = 0
    with PDFInspector(EDITED) as ins:
        show_spans("all spans AFTER edit", ins)
        print("\nverifying replacements kept formatting:")
        for needle, (exp_font_substr, exp_size, exp_color) in expectations.items():
            hits = ins.find_text(needle)
            if not hits:
                print(f"  FAIL  {needle!r} not found in edited PDF")
                fails += 1
                continue
            s = hits[0]
            font_ok  = exp_font_substr.split("-")[0].lower() in s.font.lower()
            size_ok  = abs(s.size - exp_size) < 0.01
            color_ok = s.color_hex == exp_color
            mark = "OK  " if (font_ok and size_ok and color_ok) else "FAIL"
            if not (font_ok and size_ok and color_ok):
                fails += 1
            print(f"  {mark} {needle!r:<14} font={s.font:<22} size={s.size}  color={s.color_hex}"
                  + ("" if font_ok else f"   (expected font ~ {exp_font_substr})")
                  + ("" if size_ok else f"   (expected size {exp_size})")
                  + ("" if color_ok else f"   (expected color {exp_color})"))

    print(
        "\n[5] done.\n"
        f"    Sample : {SAMPLE}\n"
        f"    Edited : {EDITED}\n"
        f"    Open both side-by-side to compare visually.\n"
    )
    return 1 if fails else 0


if __name__ == "__main__":
    raise SystemExit(main())
